version: '3.8'

services:
  app:
    container_name: erp-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    pull_policy: always
    env_file:
      - .env
    ports:
      - 5173:5173

volumes:
  data:
